export const options = [
  { value: 'value-xyy-1', label: 'label-XYY-1' },
  { value: 'value-xyy-2', label: 'label-XYY-2' },
  { value: 'value-xyy-3', label: 'label-XYY-3' },
  { value: 'value-xyy-4', label: 'label-XYY-4' },
  { value: 'value-xyy-5', label: 'label-XYY-5' },
  { value: 'value-xyy-6', label: 'label-XYY-6' },
  { value: 'value-xyy-7', label: 'label-XYY-7' },
  { value: 'value-xyy-8', label: 'label-XYY-8' },
  { value: 'value-xyy-9', label: 'label-XYY-9' },
  { value: 'value-xyy-10', label: 'label-XYY-10' },
  { value: 'value-xyy-11', label: 'label-XYY-11' },
  { value: 'value-xyy-12', label: 'label-XYY-12' },
  { value: 'value-xyy-13', label: 'label-XYY-13' },
]
