export const options = [
  { value: 'value-lucy-1', label: 'label-Lucy-1' },
  { value: 'value-lucy-2', label: 'label-Lucy-2' },
  { value: 'value-lucy-3', label: 'label-Lucy-3' },
  { value: 'value-lucy-4', label: 'label-Lucy-4' },
  { value: 'value-lucy-5', label: 'label-Lucy-5' },
  { value: 'value-lucy-6', label: 'label-Lucy-6' },
  { value: 'value-lucy-7', label: 'label-Lucy-7' },
  { value: 'value-lucy-8', label: 'label-Lucy-8' },
  { value: 'value-lucy-9', label: 'label-Lucy-9' },
  { value: 'value-lucy-10', label: 'label-Lucy-10' },
  { value: 'value-lucy-11', label: 'label-Lucy-11' },
  { value: 'value-lucy-12', label: 'label-Lucy-12' },
  { value: 'value-lucy-13', label: 'label-Lucy-13' },
]
